# Generated by Django 5.1.3 on 2025-09-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='surface',
        ),
        migrations.AddField(
            model_name='propriete',
            name='caracteristique',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='statut',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
