# Generated by Django 5.1.3 on 2025-09-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='commune',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
