# Generated by Django 5.1.3 on 2025-09-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_remove_propriete_surface_propriete_caracteristique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='statut_autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='type_autre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu'), ('en_netoyage', 'En nettoyage'), ('en_construction', 'En construction'), ('autre', 'Autre')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('villa', 'Villa'), ('immeuble', 'Immeuble'), ('magasin', 'Magasin'), ('autre', 'Autre')], max_length=50),
        ),
    ]
