# Generated by Django 5.1.3 on 2025-09-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0002_alter_propriete_commune_alter_propriete_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='supprime_par_proprietaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='supprime_par_utilisateur',
            field=models.BooleanField(default=False),
        ),
    ]
