# Generated by Django 5.1.3 on 2025-09-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_propriete_statut_autre_propriete_type_autre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='caracteristique',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='statut_autre',
        ),
        migrations.RemoveField(
            model_name='propriete',
            name='type_autre',
        ),
        migrations.AlterField(
            model_name='propriete',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu'), ('en_netoyage', 'En netoyage'), ('en_construction', 'En construction')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('villa', 'Villa'), ('immeuble', 'immeuble'), ('magasin', 'magasin')], max_length=50),
        ),
    ]
