# Generated by Django 5.1.3 on 2025-09-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_contact_supprime_par_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='supprime_par_destinataire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_par_expediteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_pour_tous',
            field=models.BooleanField(default=False),
        ),
    ]
