# Generated by Django 5.1.3 on 2025-09-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_remove_propriete_caracteristique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='type',
            field=models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain'), ('villa', 'Villa'), ('immeuble', 'Immeuble'), ('magasin', 'Magasin')], max_length=50),
        ),
    ]
