# Generated by Django 5.1.3 on 2025-10-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0004_message_supprime_par_destinataire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visite',
            name='date_visite',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='visite',
            constraint=models.UniqueConstraint(fields=('propriete', 'utilisateur'), name='unique_property_view'),
        ),
    ]
