# Generated by Django 5.1.3 on 2025-09-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0005_alter_propriete_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='caracteristique',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
