# Generated by Django 6.0.1 on 2026-03-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0005_alter_visite_date_visite_visite_unique_property_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_lu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
