# Generated by Django 6.0.1 on 2026-03-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0006_message_date_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='approuve',
            field=models.BooleanField(default=False),
        ),
    ]
