# Generated by Django 5.1.3 on 2025-09-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0007_information_message_temoignage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='caracteristique',
        ),
        migrations.AddField(
            model_name='propriete',
            name='caracteristiques',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propriete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proprietes/images/'),
        ),
        migrations.AddField(
            model_name='propriete',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='proprietes/videos/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/'),
        ),
    ]
