# Generated by Django 6.0.1 on 2026-03-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0007_propriete_approuve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='approuve',
        ),
        migrations.AddField(
            model_name='propriete',
            name='statut_propriete',
            field=models.BooleanField(default=False),
        ),
    ]
