# Generated by Django 6.0.1 on 2026-03-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_remove_propriete_approuve_propriete_statut_propriete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='statut_propriete',
        ),
        migrations.AddField(
            model_name='propriete',
            name='statut_propriete_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propriete',
            name='statut_propriete_owner',
            field=models.BooleanField(default=True),
        ),
    ]
