# Generated by Django 5.1.3 on 2025-09-07 00:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0008_remove_propriete_caracteristique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='caracteristiques',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
