# Generated by Django 6.0.1 on 2026-03-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_remove_propriete_statut_propriete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='statut_propriete_owner',
            field=models.BooleanField(default=False),
        ),
    ]
