# Generated by Django 5.1.3 on 2025-09-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0009_alter_propriete_caracteristiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriete',
            name='localisation',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
