# Generated by Django 6.0.1 on 2026-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_alter_propriete_statut_propriete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cni',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/cni/', verbose_name="Carte Nationale d'Identité"),
        ),
    ]
