# Generated by Django 5.1.3 on 2025-09-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_alter_propriete_localisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propriete',
            name='localisation',
        ),
    ]
