# Generated by Django 6.0.1 on 2026-03-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0011_utilisateur_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cni_verifie',
            field=models.BooleanField(default=False, verbose_name='CNI vérifiée'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cni',
            field=models.ImageField(default='', upload_to='utilisateurs/cni/', verbose_name="Carte Nationale d'Identité"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
