# Generated by Django 5.1.3 on 2025-09-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0011_remove_propriete_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='duree_video',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de la vidéo en secondes.', null=True),
        ),
    ]
