# Generated by Django 6.0.1 on 2026-03-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0012_utilisateur_cni_verifie_alter_utilisateur_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
