# Generated by Django 5.2.6 on 2025-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0012_propriete_duree_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriete',
            name='commune',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propriete',
            name='ville',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propriete',
            name='duree_video',
            field=models.PositiveIntegerField(blank=True, help_text='Durée de la vidéo en secondes, calculée automatiquement.', null=True),
        ),
    ]
