# Generated by Django 6.0.1 on 2026-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0013_utilisateur_otp_attempts_utilisateur_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='propriete',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='moderateur',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='propriete',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='information',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='temoignage',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='propriete',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='utilisateur',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='cni',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateurs/cni/', verbose_name="Carte Nationale d'Identité"),
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='Alerte',
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Temoignage',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
