"""
Django settings for imb project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# Configure le chemin d'accès à l'exécutable FFmpeg pour la bibliothèque moviepy
# REMPLACEZ 'C:/chemin/vers/votre/dossier/ffmpeg/bin/ffmpeg.exe' par le chemin réel
os.environ["IMAGEIO_FFMPEG_EXE"] = r"C:\Users\DAH ERIC\Downloads\ffmpeg-8.0-essentials_build\bin\ffmpeg.exe"


# MEDIA_URL, MEDIA_ROOT etc.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# ===== AJOUTEZ CES CONFIGURATIONS DE SESSION =====

# Session configuration (AJOUTER CES LIGNES)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Utilise la base de données pour les sessions
SESSION_COOKIE_AGE = 2592000        # 30 jours (1 mois)
SESSION_SAVE_EVERY_REQUEST = True  # Sauvegarde la session à chaque requête
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Ne pas expirer à la fermeture du navigateur

# Cookie configuration (AJOUTER CES LIGNES)
SESSION_COOKIE_SECURE = False  # Mettre à True seulement en HTTPS
SESSION_COOKIE_HTTPONLY = True  # Empêche l'accès JavaScript aux cookies
SESSION_COOKIE_SAMESITE = 'Lax'  # Protège contre les attaques CSRF

# CSRF configuration (AJOUTER CES LIGNES)
CSRF_COOKIE_SECURE = False  # Mettre à True seulement en HTTPS
CSRF_COOKIE_HTTPONLY = False  # Doit être False pour que JavaScript puisse lire le token
CSRF_USE_SESSIONS = False  # Stocke le token CSRF dans la session au lieu d'un cookie
CSRF_COOKIE_SAMESITE = 'Lax'

# Ajoutez ces lignes dans settings.py après les configurations de session
# Pour s'assurer que les sessions sont bien sauvegardées
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'


# Pour le débogage (AJOUTER TEMPORAIREMENT)
import logging
logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

# Logger pour les sessions (AJOUTER)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.contrib.sessions': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'django.contrib.auth': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u!%c^v&i)w111x0vzz4+@&603()9vhdvz188tg@s0#05u*o5s+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "imb-cmxe.onrender.com",      # Votre URL Render
    "immoplus.com",               # Votre futur domaine (si vous l'avez)
    "www.immoplus.com",           # Avec ou sans www
    "frereric.pythonanywhere.com", # Votre ancien hébergement
    "127.0.0.1",
    "localhost",
]


LOGOUT_REDIRECT_URL = 'login' 
# settings.py
AUTH_USER_MODEL = 'immobilier.Utilisateur'
# des ajout pour cloudinary pour l'upload des images et vidéos ebergées sur le cloud






AUTHENTICATION_BACKENDS = [
    'immobilier.backends.EmailOrUsernameModelBackend',  # login avec email/username
    'django.contrib.auth.backends.ModelBackend',       # sécurité : fallback
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'immobilier',
    
    'django_extensions',
    'django.contrib.humanize',
     'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'immobilier.middleware.SessionDebugMiddleware',  # Ajoutez ceci
]

ROOT_URLCONF = 'imb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'immobilier.context_processors.notifications',  # Ajout du context processor pour les notifications
            ],
        },
    },
]

WSGI_APPLICATION = 'imb.wsgi.application'
# Augmente la limite pour les fichiers envoyés à 5 mégaoctets (5 * 1024 * 1024 octets)
# 5 Mo est souvent un bon compromis.
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5 * 1024 * 1024

# Augmente également la limite de la taille totale de la requête (pour être sûr)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
   
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Remplacez ces lignes
LANGUAGE_CODE = 'fr-fr'  # Changé de 'en-us' à 'fr-fr'
TIME_ZONE = 'Africa/Abidjan'  # Changé de 'UTC' à votre fuseau horaire
USE_I18N = True
USE_TZ = True  # Gardez True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


